# Generated by Django 4.0.6 on 2024-09-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('url', models.TextField()),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField()),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://www.apex-timing.com/live-timing/kartcenter-campillos/')),
                ('config_port', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='races_single_active'),
        ),
        migrations.AddField(
            model_name='boardrequest',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.race', verbose_name='requests'),
        ),
    ]
